apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-ts-clean-arch-api-deployment
  labels:
    app: tech-challenge-ts-clean-arch-api-deployment
spec:
  selector:
    matchLabels:
      app: tech-challenge-ts-clean-arch-api
  template:
    metadata:
      labels:
        app: tech-challenge-ts-clean-arch-api
    spec:
      containers:
        - name: tech-challenge-ts-clean-arch-api
          image: leosaglia/tech-challenge-ts-clean-arch
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_URL
            - name: PORT
              value: "3001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
