apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tech-challenge-ts-clean-arch-postgres-statefulset
  labels:
    app: tech-challenge-ts-clean-arch-postgres-statefulset
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-ts-clean-arch-postgres
  template:
    metadata:
      labels:
        app: tech-challenge-ts-clean-arch-postgres
    spec:
      containers:
        - name: tech-challenge-ts-clean-arch-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc