apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespass
  POSTGRES_URL: postgresql://postgres:postgrespass@tech-challenge-ts-clean-arch-postgres:5432/techchallenge-fastfood?schema=public
